echo "Copying to Unreal"
cd "C:\Users\Herbert\Development\github\libnox"
copy x64\Release\libnox.lib "C:\Users\Herbert\Documents\Unreal Projects\NoxUnreal\ThirdParty\libnox\Libraries\libnox.x64.lib"
copy src\libnox.h "C:\Users\Herbert\Documents\Unreal Projects\NoxUnreal\ThirdParty\libnox\Includes"
copy src\noxtypes.h "C:\Users\Herbert\Documents\Unreal Projects\NoxUnreal\ThirdParty\libnox\Includes"
